### ISSUE TITLE
I got following error

### ISSUE THREAD

**Issue by PeterZong** [Swagger-Net/Swagger.Net#32]
I am building a WebApi with .NET 4.5, but got the following error:

Method 'GetDocumentation' in type 'Swagger.Net.XmlCommentDocumentationProvider' from assembly 'Swagger.Net, Version=0.5.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation. 

Any suggestion?

.NET 4.0 works fine.

**Comment by DanOertelt** [comment]
Yes, the same error. Me thinks it is because of the current implementation not support .NET 4.5, only .NET 4.0.

**Comment by PeterZong** [comment]
Yes, now I use Swashbuckle to generate Swagger for ASP.NET Web API.
